server:
  port: 8030

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zch752306614/springcloudConfig/
          search-paths: respo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

